### ISSUE TITLE
great readme!!

### ISSUE THREAD

**Issue by georgiamshaw** [fac18/week4-gmno-autocomplete#27]
just wanted to leave a quick note and say how fantastic your readme is!! well done for putting so much effort into it - it really pays off!

just don't forget to leave instructions on how I can set up and run the project!

also - well done for not being scared to say you're scared of how many heritage sites there are, and deciding to break the project down a bit! that definitely held my group back in week 4.

and fantastic file structure.

**Comment by georgiamshaw** [comment]
P.S. I'm just a slack away if you need any clarification/help on any of the issues!!

**Comment by renatajarmova** [comment]
Georgia, thank you for all the compliments , suggestions and for spotting those bugs for us! We're working to solve them  💪
