### ISSUE TITLE
small unwanted black thing in search bar (before typing)

### ISSUE THREAD

**Issue by sleepysnapdragon** [fac18/week4-gmno-autocomplete#33]
<img width="145" alt="Screen Shot 2019-11-22 at 10 54 10" src="https://user-images.githubusercontent.com/28454190/69420386-7e710880-0d16-11ea-92bb-a33695926e59.png">

I think it might be because of the placeholder value in the HTML? there is a big space before the last word ('here....')

**Comment by pat-cki** [comment]
Thanks for spotting this on
